### ISSUE TITLE
How to fix "missing function body" build for mips, thank you !

### ISSUE THREAD

**Issue by hongjinlin** [remyoudompheng/bigfft#5]
macOS 10.14.4 (18E226)

go version go1.11.2 darwin/amd64

go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/hongjinlin/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/hongjinlin/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/1q/3d6q6x2s6057s6fgwdxr7ffw0000gn/T/go-build945892395=/tmp/go-build -gno-record-gcc-switches -fno-common"

build commond:
env GOOS=linux GOARCH=mipsle GOMIPS=softfloat  go build -ldflags="-s -w" main.go

errors:
# github.com/remyoudompheng/bigfft
../github.com/remyoudompheng/bigfft/arith_decl.go:10:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:11:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:12:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:13:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:14:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:15:6: missing function body
../github.com/remyoudompheng/bigfft/arith_decl.go:16:6: missing function body

**Comment by remyoudompheng** [comment]
Can you try again after commit babf203 ?

**Comment by hongjinlin** [comment]
> Can you try again after commit [babf203](https://github.com/remyoudompheng/bigfft/commit/babf20351dd7e3ac320adedbbe5eb311aec8763c) ?
Its ok now thank you very much!!!

**Comment by zz-jason** [comment]
I meet the same problem while compiling https://github.com/pingcap/tidb on a PowerPC computer:

```
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:10:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:11:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:12:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:13:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:14:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:15:6: missing function body
/opt/gopath/pkg/mod/github.com/remyoudompheng/bigfft@v0.0.0-20190512091148-babf20351dd7/arith_decl.go:16:6: missing function body
make: *** [server] Error 2
```

remyoudompheng/bigfft version:
```
v0.0.0-20190512091148-babf20351dd7
```

go version:
```
$ go version
go version go1.13.4 linux/ppc64le
root has logged on pts/7 from 192.168.198.219.
```

OS version:
```
$ cat /proc/version
Linux version 4.14.0-115.el7a.ppc64le (mockbuild@ppc-055.build.eng.bos.redhat.com) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)) #1 SMP Tue Sep 25 12:28:39 EDT 2018
```

I think maybe the reason is there isn't an assembly code for the ppc architecture:
```
$ ls -l
total 100
-r--r--r-- 1 tidb tidb  1479 Nov 23 00:58 LICENSE
-r--r--r-- 1 tidb tidb  1693 Nov 23 00:58 README
-r--r--r-- 1 tidb tidb  1038 Nov 23 00:58 arith_386.s
-r--r--r-- 1 tidb tidb  1038 Nov 23 00:58 arith_amd64.s
-r--r--r-- 1 tidb tidb  4555 Nov 23 00:58 arith_arm.s
-r--r--r-- 1 tidb tidb  8806 Nov 23 00:58 arith_arm64.s
-r--r--r-- 1 tidb tidb   520 Nov 23 00:58 arith_decl.go
-r--r--r-- 1 tidb tidb  1065 Nov 23 00:58 arith_mips64x.s
-r--r--r-- 1 tidb tidb  1061 Nov 23 00:58 arith_mipsx.s
dr-xr-xr-x 2 tidb tidb   105 Nov 23 00:58 benchmarks
-r--r--r-- 1 tidb tidb  3695 Nov 23 00:58 calibrate_test.go
-r--r--r-- 1 tidb tidb  4081 Nov 23 00:58 fermat.go
-r--r--r-- 1 tidb tidb  5006 Nov 23 00:58 fermat_test.go
-r--r--r-- 1 tidb tidb  9960 Nov 23 00:58 fft.go
-r--r--r-- 1 tidb tidb 10265 Nov 23 00:58 fft_test.go
-r--r--r-- 1 tidb tidb    49 Nov 23 00:58 go.mod
-r--r--r-- 1 tidb tidb  1689 Nov 23 00:58 scan.go
-r--r--r-- 1 tidb tidb  1899 Nov 23 00:58 scan_test.go
```

I can't see a file like `arith_ppc.s`.

**Comment by remyoudompheng** [comment]
You are using an old version. See issue #6 already fixed.

**Comment by zz-jason** [comment]
> You are using an old version. See issue #6 already fixed.

Got it, I can successfully build the binary with the latest `remyoudompheng/bigfft`. Thanks for your help.
